export const SAVE_TARGET_VALUE = "SAVE_TARGET_VALUE";
export const VALIDATION_REQUIRED_FAILED = "VALIDATION_REQUIRED_FAILED";
export const VALIDATION_REQUIRED_SUCCESS = "VALIDATION_REQUIRED_SUCCESS";
export const VALIDATION_WORD_LIMITS_OK = "VALIDATION_WORD_LIMITS_OK";
export const VALIDATION_WORD_LIMITS_NOT_OK = "VALIDATION_WORD_LIMITS_NOT_OK";
export const SET_FIELD_ON_BLUR = "SET_FIELD_ON_BLUR";
export const EMAIL_VALIDATION_FAILED = "EMAIL_VALIDATION_FAILED";
export const EMAIL_VALIDATION_SUCCESS = "EMAIL_VALIDATION_SUCCESS";
export const DATE_VALIDATION_SUCCESS = "DATE_VALIDATION_SUCCESS";
export const DATE_VALIDATION_FAILED = "DATE_VALIDATION_FAILED";
export const TIME_VALIDATION_SUCCESS = "TIME_VALIDATION_SUCCESS";
export const TIME_VALIDATION_FAILED = "TIME_VALIDATION_FAILED";
export const DUPLICATE_VALIDATION_FAILED = "DUPLICATE_VALIDATION_FAILED";
export const DUPLICATE_VALIDATION_SUCCESS = "DUPLICATE_VALIDATION_SUCCESS";
export const DUPLICATE_TITLES_INIT = "DUPLICATE_TITLES_INIT";

export const INIT_LOGGED_USER_DATA = "INIT_LOGGED_USER_DATA";
